### 新增一个定时任务

POST http://localhost:8000/batch/admin/job/add
Content-Type: application/json

{
  "name": "top.yuanql.train.batch.job.TestJob",
  "jobGroupName": "default",
  "cronExpression": "*/2 * * * * ?",
  "desc": "test job"
}

### 查询定时任务

GET http://localhost:8000/batch/admin/job/query

### 暂停定时任务

POST http://localhost:8000/batch/admin/job/pause
Content-Type: application/json

{
  "name": "top.yuanql.train.batch.job.TestJob",
  "jobGroupName": "default"
}

### 重启定时任务

POST http://localhost:8000/batch/admin/job/resume
Content-Type: application/json

{
  "name": "top.yuanql.train.batch.job.TestJob",
  "jobGroupName": "default"
}

### 重置定时任务

POST http://localhost:8000/batch/admin/job/reschedule
Content-Type: application/json

{
"name": "top.yuanql.train.batch.job.TestJob",
"jobGroupName": "default",
"cronExpression": "*/5 * * * * ?",
"desc": "test job"
}

### 删除定时任务

POST http://localhost:8000/batch/admin/job/delete
Content-Type: application/json

{
"name": "top.yuanql.train.batch.job.TestJob",
"jobGroupName": "default"
}

###

POST http://localhost:8000/batch/admin/job/run
Content-Type: application/json

{
"name": "top.yuanql.train.batch.job.DailyTrainJob",
"jobGroupName": "default"
}
