
### 测试passenger插入新数据

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "grfgfdtest001",
  "idCard": "1223344",
  "type": "1"
}

### 测试passenger编辑数据

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1682260954986975232,
  "memberId": 1678395468868096000,
  "name": "grfgfd11111111",
  "idCard": "1223344",
  "type": "1"
}

### 查询乘车人列表
GET http://localhost:8000/member/passenger/query-list?page=1&size=4
Content-Type: application/json
token: {{token}}


###

