
### 测试 member 模块
GET http://localhost:8081/member/hello
Accept: application/json


### 测试gateway模块
GET http://localhost:8000/member/hello
Accept: application/json


###


GET http://localhost:8000/member/member/count
Accept: application/json

###


POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=213123

###

POST http://localhost:8000/member/member/send_code
Content-Type: application/x-www-form-urlencoded

mobile=12345678901

###

POST http://localhost:8000/member/member/login
Content-Type: application/x-www-form-urlencoded

mobile=12345678901&code=8888

###

