
### 测试passenger插入新数据

POST http://localhost:8000/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "test001",
  "idCard": "1223344",
  "type": "1"
}

### 查询乘车人列表
GET http://localhost:8000/member/passenger/query-list
Content-Type: application/json
token: {{token}}


###

